<?php

use Illuminate\Database\Seeder;

class ProjectTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    DB::table('projects')->insert([
      ['title' => 'S社オフィス', 'top_image' => "", 'explain' => 'AIスタートアップ会社のオフィス改修計画です。全体を３つのゾーンである静かな森、森の広場、森のラウンジに分けます。床はフローリングを主として、廊下側の壁面には緑が生茂る"greenwall"が広がり、全体の森の感じをつくります。北側にはバーカウンター、中央には大きなコラボレーションができる机とダイナー席、南側には静かに集中できるパーソナルゾーンをつくります。それぞれの場所で特徴をつくりながらも、全体で様々な活動が広がるワンルームの森をつくります。', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "1", 'thumbnail_id' => "1", 'brand_id' => '1'],
      ['title' => '東松山の家', 'top_image' => "", 'explain' => 'LocatedinSaitama,HigashimatsuyamaHousewasdesignedforacouplewhosefamilieslivedonthesiteforgenerationsforover300years.Iattempttokeepandpassonthefamilymemoryinthebuildingstothenewspace.Inordertomaketheexistingbuilding,thegarden,thesurroundingnatureandthenewextensionsectionasonepiece,wefixedandaddedthestructurebasedoneachbuildingsconditionwithusingthecommonmaterialbetweentheexistingandtheextensionsection.Despiteallthedifferentstructures,itbecame“onehouse”liketheyareholdinghandswitheachother', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "1", 'thumbnail_id' => "1", 'brand_id' => '2'],
      ['title' => '笹沼邸', 'top_image' => "", 'explain' => 'ひとつの建物の中に、専用住宅と賃貸住宅2戸を内包する計画である。敷地は旗竿敷地で、周辺に2～3階建ての住宅やマンションが立ち並ぶ街区の中央に位置しながらも、南側と西側は開かれた明るい大きな場所だった。賃貸に出す部屋は、学生や若い社会人などを想定したワンルームで、数年で住み手が変わり、それぞれの生活スタイルや、家にいる時間帯も異なるだろうと思った。一方、専用住宅は、建主が長くこの地で暮らし、家族と共に年月を重ねていこうと考えていた。大きく性格の異なるこれらの住空間をひとつの敷地に考えるにあたって、お互いが同じ敷地に存在するからこそ、それぞれの空間がより豊かになるような関係性にしたいと思った。', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "1", 'thumbnail_id' => "1", 'brand_id' => '3'],
      ['title' => 'OfficewithaPatio', 'top_image' => "", 'explain' => '東京都港区にある広告製作会社のオフィス移転プロジェクト。インターオフィスでは、家具と特注家具を担当した。コンセプトは中庭があるオフィス。グリーンを効果的に配置し、オフィスに居ながらも、自然と近く接することができる空間となった。', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "1", 'thumbnail_id' => "1", 'brand_id' => '4'],
      ['title' => 'HouseofWindandLight', 'top_image' => "", 'explain' => 'このプロジェクトでは、「未来の住宅」について考えている。', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "2", 'thumbnail_id' => "2", 'brand_id' => '4'], ['title' => 'OitaMiraiShinkinBank', 'top_image' => "", 'explain' => '住宅とは本来、社会環境を色濃く反映し、その時代の価値観、振る舞い、生活によって部屋や動線が構成されている。住宅の変化で大きな部分としては、日本の場合、「畳での生活→椅子での生活」に変わったように、ライフスタイルの変化＝住まいの進化であると言える。つまり、未来の家を想像するということは未来の社会や暮らしを想像するということと同義ではないかと思う。', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "3", 'thumbnail_id' => "3", 'brand_id' => '5'],
      ['title' => 'Toy’sFactory', 'top_image' => "", 'explain' => 'Thisisanofficewedesignedforamusiclabel,occupyinganentirefloorofabuildinglocatedatafive-roadjunctioninShibuyawhereMiyamasuzaka,aslopingstreettraversingShibuyastation,andRoute246intersect.Theofficespacehaswindowsallaroundthefoursides,andonefeelsasiffloatingaboveRoute246whenstandingnearwindowsonthenorthside.Inordertomakebestuseofthesewindowspaces,wemadeacentralcoreplanandlocatedameetingroom,storageandcafeinsidethecore.Roomswithdifferentfunctionsandcharacteristics,namelyanoffice,lounge,andartistsroomarelocatedaroundthecoreinsuchawaythateachroomisconnectedtoarelatedfunctionofaroominthecoreandalsofacingthemostidealwindowconditionforitsuse.Forexample,thespaceinfrontofthestorageandthemeetingspacebecomesafreeaddressoffice;thelight-filledsoutheastwindowspaceinfrontofthecafelocatedinthecorebecomesareceptionlounge;andthespacebetweenthenortheastwindowsandthereceptioncounter,whereoneexperiencesaspectacularfeelingoffloatingabovethecity,accommodatesaspatialsequenceconnectingthedirector’sroom,boardroomandVIProom,andartistsroom.Thesespaceslooselyconnectwitheachotherandformacontinuousopenspacearoundthecentralcore,whereonefeelsthelightandcityvibrancyeverywhere.Thefloorlevelofthiscontinuousspaceishighestattheexecutiveroomandartistsroom,whichgraduallydescendstothelowestpointattheentrancespaceandofficeonthesouthside.Airconditionersareinstalledinthespaceunderallwindowsalongtheentireperimeter,andtheabove-windowspaceisusedindifferentwaysaccordingtothefloorlevelofeachspace.Forexample,thetopoftheairconditionerisalmostlevelwiththefloorattheexecutiveroom,creatinganimpressionofcompleteopennesswhereonefeelslikeflyingouttothesky;attheentrancespacewherethefloorislowest,thetopoftheairconditionerrisesabovethefloorandisusedasacountertop;andinthespacesattheintermediatefloorlevel,itisusedasseatingarea.', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "4", 'thumbnail_id' => "4", 'brand_id' => '6'],
      ['title' => 'BIGsNewYorkoffice', 'top_image' => "", 'explain' => 'ArchitecturefirmBIGhasmoveditsNewYorkofficefromtheFinancialDistricttoBrooklyn,allowingthestudiotoexpanditsworkshopandenjoyaprivatepatiooverlookingManhattan.', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "5", 'thumbnail_id' => "5", 'brand_id' => '7'],
      ['title' => 'Indeed’sBiophilicTokyoOffice', 'top_image' => "", 'explain' => 'Indeed’snewofficeinthequicklygrowingAzabudistrictofTokyoreflectsthecompany’suniquestrategy—toprovideworkenvironmentsthatincorporatethemostup-to-datethinkingpossible,whilealsointegratingthecharacterofthespecificplacewheretheofficeislocated.Thisofficehasalltheamenitiesexpectedinamoderntechoffice,includinglounges,coffeebars,gamerooms,andthelatestinAVandconnectivity.ButitalsohasamaterialandformalconnectiontotraditionalelementsofJapaneseculturewithoutresortingtoliteralinterpretationsorkitsch.', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "6", 'thumbnail_id' => "6", 'brand_id' => '8'], ['title' => 'Workstories’CoolNewLondonOffice', 'top_image' => "", 'explain' => 'Workstories,adesigncompanythatcuratescommercialfurniturefromaglobalcommunity,recentlyhiredworkplacedesignfirmThirdwayInteriorstodesigntheirnewofficeinLondon,England.', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "7", 'thumbnail_id' => "7", 'brand_id' => '9'],
      ['title' => 'Compass’NewYorkCityHQ', 'top_image' => "", 'explain' => 'Compass,atechnology-drivenrealestatecompanythathelpspeoplefindtheirdreamhome,recentlyhiredarchitecturalanddesignfirmVocontodesigntheinterioroftheirNYCheadquartersinUnionSquare.', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "8", 'thumbnail_id' => "8", 'brand_id' => '10'], ['title' => 'SecondHome', 'top_image' => "", 'explain' => 'Theco-workingspacethattheSelgasCanostudiohascreatedinsidetheoldestmarketinLisbonisknownasSecondHome.It’safriendlyandflexibleplacethatactsasameetingplace,butalsoallowsforrelaxationandphysicalexercise', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "9", 'thumbnail_id' => "9", 'brand_id' => '11'], ['title' => '伊丹の住宅', 'top_image' => "", 'explain' => '-', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "10", 'thumbnail_id' => "10", 'brand_id' => '12'], ['title' => '虹をさがす家', 'top_image' => "", 'explain' => '北傾斜の高台に建つ住宅である。敷地地盤が道路より低く、北側斜線が厳しかったため、抜け感の良い北側テラスを眺めながら暮らすプランとした。ただし北向き住戸は暗い。南側は採光を得ようにも道路があり、歩行者からの視線や騒音が問題だった。そこで遮音効果を高める質量と、透過性を併せもつ無垢のガラス角棒を南側の吹き抜けいっぱいに積層させた。85mm角のガラス棒の断面形状は、冬季は室内奥にまで太陽光を入れ、夏季は大半の光を遮りつつも淡い光が拡散する角度にカットした。その結果、日時計のように、時間帯や季節によって様々な光のうつろいが現れることとなった。夜明けの青い光や日没前の燃えるような光、月光。様々な色で空間が染まる。朝は東からの光がキッチンに伸び、夕方は一日のなごりを惜しむようにリビングに光が差し込む。光が人のふるまいを導き、光が人のふるまいを追いかけるように包み込む。竣工後、施主から嬉しい手紙が届いた。そこには、「この家は時間帯によって異なる場所に虹が現れる。それを発見するのが楽しい。」と書かれていた。プリズムガラスが生活を彩る家である。', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "11", 'thumbnail_id' => "11", 'brand_id' => '13'], ['title' => 'HouseC―地層の家―', 'top_image' => "", 'explain' => '房総半島の海辺に建つ週末住宅である。周囲には地層がむき出しになった崖と草原が広がっている。普段都心の高層マンションに住む施主は、週末だけは大地と接して暮らしたいと願っていた。そこで、敷地の土を屋根や壁に用いて、大地と連続した建築を提案した。', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "12", 'thumbnail_id' => "12", 'brand_id' => '13'], ['title' => 'SILHOUTTEHYTTE', 'top_image' => "", 'explain' => '-', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "13", 'thumbnail_id' => "13", 'brand_id' => '14'], ['title' => 'houseT/salonT', 'top_image' => "", 'explain' => 'ファッションデザイナー家族のためのアトリエ・多目的サロンを併設した職住一体型住居。', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "14", 'thumbnail_id' => "14", 'brand_id' => '15'], ['title' => 'TheTreetopsVillainByronBay', 'top_image' => "", 'explain' => '-', 'postal_code' => "", 'prefecture' => '13', 'address' => "", 'address_url' => "", 'is_accepted' => "15", 'thumbnail_id' => "15", 'brand_id' => '16'],
    ]);
  }
}
